# URL the site will be built for
base_url = "https://giannirosato.com"

# automatically compile sass files in the sass directory
compile_sass = true

# build a search index to be used later on by a JS lib
build_search_index = false

# atom feed
generate_feeds = true
feed_filenames = ["atom.xml"]
title = "Gianni Rosato"
author = "Gianni Rosato"
description = "Hi, I'm Gianni. I build video & image compression technology for a more beautiful Internet."

# syntax highlighting
[markdown]
[markdown.highlighting]
error_on_missing_language = true
# inline hex colours (`inline`) or css classes (`class`)
style = "inline"
theme = "vitesse-black"

[extra]
